# Generated by Django 4.0.5 on 2022-07-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=747)),
                ('email', models.EmailField(max_length=254)),
                ('departament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.departament')),
            ],
        ),
    ]
