# Generated by Django 4.0.6 on 2022-07-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departament',
            new_name='Department',
        ),
        migrations.AlterModelOptions(
            name='employ',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.RenameField(
            model_name='employ',
            old_name='departament',
            new_name='department',
        ),
    ]
